"""Display names and hardware boards for Apple mobile devices.

These tables describe devices; they do not restrict compatibility.
"""

IPHONE_MODELS = {
    'iPhone13,2': {'name': 'iPhone 12', 'boards': ['D53GAP']},
    'iPhone13,1': {'name': 'iPhone 12 mini', 'boards': ['D52GAP']},
    'iPhone13,3': {'name': 'iPhone 12 Pro', 'boards': ['D53PAP']},
    'iPhone13,4': {'name': 'iPhone 12 Pro Max', 'boards': ['D54PAP']},
    'iPhone14,5': {'name': 'iPhone 13', 'boards': ['D17AP']},
    'iPhone14,4': {'name': 'iPhone 13 mini', 'boards': ['D16AP']},
    'iPhone14,2': {'name': 'iPhone 13 Pro', 'boards': ['D63AP']},
    'iPhone14,3': {'name': 'iPhone 13 Pro Max', 'boards': ['D64AP']},
    'iPhone14,7': {'name': 'iPhone 14', 'boards': ['D27AP']},
    'iPhone14,8': {'name': 'iPhone 14 Plus', 'boards': ['D28AP']},
    'iPhone15,2': {'name': 'iPhone 14 Pro', 'boards': ['D73AP']},
    'iPhone15,3': {'name': 'iPhone 14 Pro Max', 'boards': ['D74AP']},
    'iPhone15,4': {'name': 'iPhone 15', 'boards': ['D37AP']},
    'iPhone15,5': {'name': 'iPhone 15 Plus', 'boards': ['D38AP']},
    'iPhone16,1': {'name': 'iPhone 15 Pro', 'boards': ['D83AP']},
    'iPhone16,2': {'name': 'iPhone 15 Pro Max', 'boards': ['D84AP']},
    'iPhone17,4': {'name': 'iPhone 16 Plus', 'boards': ['D48AP']},
    'iPhone17,2': {'name': 'iPhone 16 Pro Max', 'boards': ['D94AP']},
    'iPhone17,3': {'name': 'iPhone 16', 'boards': ['D47AP']},
    'iPhone17,1': {'name': 'iPhone 16 Pro', 'boards': ['D93AP']},
    'iPhone17,5': {'name': 'iPhone 16e', 'boards': ['V59AP']},
    'iPhone18,1': {'name': 'iPhone 17 Pro', 'boards': ['V53AP']},
    'iPhone18,2': {'name': 'iPhone 17 Pro Max', 'boards': ['V54AP']},
    'iPhone18,4': {'name': 'iPhone Air', 'boards': ['D23AP']},
    'iPhone18,3': {'name': 'iPhone 17', 'boards': ['V57AP']},
    'iPhone18,5': {'name': 'iPhone 17e', 'boards': ['V159AP']},
    'iPhone19,7': {'name': 'iPhone 18 Pro Max', 'boards': ['V64SAP']},
    'iPhone19,3': {'name': 'iPhone 18 Pro Max (U.S.)', 'boards': ['V64AP']},
    'iPhone19,2': {'name': 'iPhone 18 Pro', 'boards': ['V63AP']},
}

# iPad identifiers and boards: https://github.com/libimobiledevice/libirecovery/blob/master/src/libirecovery.c
IPAD_MODELS = {
    'iPad1,1': {'name': 'iPad', 'boards': ['K48AP']},
    'iPad2,1': {'name': 'iPad 2 (Wi-Fi)', 'boards': ['K93AP']},
    'iPad2,2': {'name': 'iPad 2 (GSM)', 'boards': ['K94AP']},
    'iPad2,3': {'name': 'iPad 2 (CDMA)', 'boards': ['K95AP']},
    'iPad2,4': {'name': 'iPad 2 (Wi-Fi) R2 2012', 'boards': ['K93AAP']},
    'iPad2,5': {'name': 'iPad mini (Wi-Fi)', 'boards': ['P105AP']},
    'iPad2,6': {'name': 'iPad mini (GSM)', 'boards': ['P106AP']},
    'iPad2,7': {'name': 'iPad mini (Global)', 'boards': ['P107AP']},
    'iPad3,1': {'name': 'iPad (3rd gen, Wi-Fi)', 'boards': ['J1AP']},
    'iPad3,2': {'name': 'iPad (3rd gen, CDMA)', 'boards': ['J2AP']},
    'iPad3,3': {'name': 'iPad (3rd gen, GSM)', 'boards': ['J2AAP']},
    'iPad3,4': {'name': 'iPad (4th gen, Wi-Fi)', 'boards': ['P101AP']},
    'iPad3,5': {'name': 'iPad (4th gen, GSM)', 'boards': ['P102AP']},
    'iPad3,6': {'name': 'iPad (4th gen, Global)', 'boards': ['P103AP']},
    'iPad4,1': {'name': 'iPad Air (Wi-Fi)', 'boards': ['J71AP']},
    'iPad4,2': {'name': 'iPad Air (Cellular)', 'boards': ['J72AP']},
    'iPad4,3': {'name': 'iPad Air (China)', 'boards': ['J73AP']},
    'iPad4,4': {'name': 'iPad mini 2 (Wi-Fi)', 'boards': ['J85AP']},
    'iPad4,5': {'name': 'iPad mini 2 (Cellular)', 'boards': ['J86AP']},
    'iPad4,6': {'name': 'iPad mini 2 (China)', 'boards': ['J87AP']},
    'iPad4,7': {'name': 'iPad mini 3 (Wi-Fi)', 'boards': ['J85MAP']},
    'iPad4,8': {'name': 'iPad mini 3 (Cellular)', 'boards': ['J86MAP']},
    'iPad4,9': {'name': 'iPad mini 3 (China)', 'boards': ['J87MAP']},
    'iPad5,1': {'name': 'iPad mini 4 (Wi-Fi)', 'boards': ['J96AP']},
    'iPad5,2': {'name': 'iPad mini 4 (Cellular)', 'boards': ['J97AP']},
    'iPad5,3': {'name': 'iPad Air 2 (Wi-Fi)', 'boards': ['J81AP']},
    'iPad5,4': {'name': 'iPad Air 2 (Cellular)', 'boards': ['J82AP']},
    'iPad6,3': {'name': 'iPad Pro 9.7-inch (Wi-Fi)', 'boards': ['J127AP']},
    'iPad6,4': {'name': 'iPad Pro 9.7-inch (Cellular)', 'boards': ['J128AP']},
    'iPad6,7': {'name': 'iPad Pro 12.9-inch (1st gen, Wi-Fi)', 'boards': ['J98AAP']},
    'iPad6,8': {'name': 'iPad Pro 12.9-inch (1st gen, Cellular)', 'boards': ['J99AAP']},
    'iPad6,11': {'name': 'iPad (5th gen, Wi-Fi)', 'boards': ['J71SAP', 'J71TAP']},
    'iPad6,12': {'name': 'iPad (5th gen, Cellular)', 'boards': ['J72SAP', 'J72TAP']},
    'iPad7,1': {'name': 'iPad Pro 12.9-inch (2nd gen, Wi-Fi)', 'boards': ['J120AP']},
    'iPad7,2': {'name': 'iPad Pro 12.9-inch (2nd gen, Cellular)', 'boards': ['J121AP']},
    'iPad7,3': {'name': 'iPad Pro 10.5-inch (Wi-Fi)', 'boards': ['J207AP']},
    'iPad7,4': {'name': 'iPad Pro 10.5-inch (Cellular)', 'boards': ['J208AP']},
    'iPad7,5': {'name': 'iPad (6th gen, Wi-Fi)', 'boards': ['J71BAP']},
    'iPad7,6': {'name': 'iPad (6th gen, Cellular)', 'boards': ['J72BAP']},
    'iPad7,11': {'name': 'iPad (7th gen, Wi-Fi)', 'boards': ['J171AP']},
    'iPad7,12': {'name': 'iPad (7th gen, Cellular)', 'boards': ['J172AP']},
    'iPad8,1': {'name': 'iPad Pro 11-inch (1st gen, Wi-Fi)', 'boards': ['J317AP']},
    'iPad8,2': {'name': 'iPad Pro 11-inch (1st gen, Wi-Fi, 1TB)', 'boards': ['J317XAP']},
    'iPad8,3': {'name': 'iPad Pro 11-inch (1st gen, Cellular)', 'boards': ['J318AP']},
    'iPad8,4': {'name': 'iPad Pro 11-inch (1st gen, Cellular, 1TB)', 'boards': ['J318XAP']},
    'iPad8,5': {'name': 'iPad Pro 12.9-inch (3rd gen, Wi-Fi)', 'boards': ['J320AP']},
    'iPad8,6': {'name': 'iPad Pro 12.9-inch (3rd gen, Wi-Fi, 1TB)', 'boards': ['J320XAP']},
    'iPad8,7': {'name': 'iPad Pro 12.9-inch (3rd gen, Cellular)', 'boards': ['J321AP']},
    'iPad8,8': {'name': 'iPad Pro 12.9-inch (3rd gen, Cellular, 1TB)', 'boards': ['J321XAP']},
    'iPad8,9': {'name': 'iPad Pro 11-inch (2nd gen, Wi-Fi)', 'boards': ['J417AP']},
    'iPad8,10': {'name': 'iPad Pro 11-inch (2nd gen, Cellular)', 'boards': ['J418AP']},
    'iPad8,11': {'name': 'iPad Pro 12.9-inch (4th gen, Wi-Fi)', 'boards': ['J420AP']},
    'iPad8,12': {'name': 'iPad Pro 12.9-inch (4th gen, Cellular)', 'boards': ['J421AP']},
    'iPad11,1': {'name': 'iPad mini (5th gen, Wi-Fi)', 'boards': ['J210AP']},
    'iPad11,2': {'name': 'iPad mini (5th gen, Cellular)', 'boards': ['J211AP']},
    'iPad11,3': {'name': 'iPad Air (3rd gen, Wi-Fi)', 'boards': ['J217AP']},
    'iPad11,4': {'name': 'iPad Air (3rd gen, Cellular)', 'boards': ['J218AP']},
    'iPad11,6': {'name': 'iPad (8th gen, Wi-Fi)', 'boards': ['J171AAP']},
    'iPad11,7': {'name': 'iPad (8th gen, Cellular)', 'boards': ['J172AAP']},
    'iPad12,1': {'name': 'iPad (9th gen, Wi-Fi)', 'boards': ['J181AP']},
    'iPad12,2': {'name': 'iPad (9th gen, Cellular)', 'boards': ['J182AP']},
    'iPad13,1': {'name': 'iPad Air (4th gen, Wi-Fi)', 'boards': ['J307AP']},
    'iPad13,2': {'name': 'iPad Air (4th gen, Cellular)', 'boards': ['J308AP']},
    'iPad13,4': {'name': 'iPad Pro 11-inch (3rd gen, Wi-Fi)', 'boards': ['J517AP']},
    'iPad13,5': {'name': 'iPad Pro 11-inch (3rd gen, Wi-Fi, 2TB)', 'boards': ['J517XAP']},
    'iPad13,6': {'name': 'iPad Pro 11-inch (3rd gen, Cellular)', 'boards': ['J518AP']},
    'iPad13,7': {'name': 'iPad Pro 11-inch (3rd gen, Cellular, 2TB)', 'boards': ['J518XAP']},
    'iPad13,8': {'name': 'iPad Pro 12.9-inch (5th gen, Wi-Fi)', 'boards': ['J522AP']},
    'iPad13,9': {'name': 'iPad Pro 12.9-inch (5th gen, Wi-Fi, 2TB)', 'boards': ['J522XAP']},
    'iPad13,10': {'name': 'iPad Pro 12.9-inch (5th gen, Cellular)', 'boards': ['J523AP']},
    'iPad13,11': {'name': 'iPad Pro 12.9-inch (5th gen, Cellular, 2TB)', 'boards': ['J523XAP']},
    'iPad13,16': {'name': 'iPad Air (5th gen, Wi-Fi)', 'boards': ['J407AP']},
    'iPad13,17': {'name': 'iPad Air (5th gen, Cellular)', 'boards': ['J408AP']},
    'iPad13,18': {'name': 'iPad (10th gen, Wi-Fi)', 'boards': ['J271AP']},
    'iPad13,19': {'name': 'iPad (10th gen, Cellular)', 'boards': ['J272AP']},
    'iPad14,1': {'name': 'iPad mini (6th gen, Wi-Fi)', 'boards': ['J310AP']},
    'iPad14,2': {'name': 'iPad mini (6th gen, Cellular)', 'boards': ['J311AP']},
    'iPad14,3': {'name': 'iPad Pro 11-inch (4th gen, Wi-Fi)', 'boards': ['J617AP']},
    'iPad14,4': {'name': 'iPad Pro 11-inch (4th gen, Cellular)', 'boards': ['J618AP']},
    'iPad14,5': {'name': 'iPad Pro 12.9-inch (6th gen, Wi-Fi)', 'boards': ['J620AP']},
    'iPad14,6': {'name': 'iPad Pro 12.9-inch (6th gen, Cellular)', 'boards': ['J621AP']},
    'iPad14,8': {'name': 'iPad Air 11-inch (M2, Wi-Fi)', 'boards': ['J507AP']},
    'iPad14,9': {'name': 'iPad Air 11-inch (M2, Cellular)', 'boards': ['J508AP']},
    'iPad14,10': {'name': 'iPad Air 13-inch (M2, Wi-Fi)', 'boards': ['J537AP']},
    'iPad14,11': {'name': 'iPad Air 13-inch (M2, Cellular)', 'boards': ['J538AP']},
    'iPad15,3': {'name': 'iPad Air 11-inch (M3, Wi-Fi)', 'boards': ['J607AP']},
    'iPad15,4': {'name': 'iPad Air 11-inch (M3, Cellular)', 'boards': ['J608AP']},
    'iPad15,5': {'name': 'iPad Air 13-inch (M3, Wi-Fi)', 'boards': ['J637AP']},
    'iPad15,6': {'name': 'iPad Air 13-inch (M3, Cellular)', 'boards': ['J638AP']},
    'iPad15,7': {'name': 'iPad (A16, Wi-Fi)', 'boards': ['J481AP']},
    'iPad15,8': {'name': 'iPad (A16, Cellular)', 'boards': ['J482AP']},
    'iPad16,1': {'name': 'iPad mini (A17 Pro, Wi-Fi)', 'boards': ['J410AP']},
    'iPad16,2': {'name': 'iPad mini (A17 Pro, Cellular)', 'boards': ['J411AP']},
    'iPad16,3': {'name': 'iPad Pro 11-inch (M4, Wi-Fi)', 'boards': ['J717AP']},
    'iPad16,4': {'name': 'iPad Pro 11-inch (M4, Cellular)', 'boards': ['J718AP']},
    'iPad16,5': {'name': 'iPad Pro 13-inch (M4, Wi-Fi)', 'boards': ['J720AP']},
    'iPad16,6': {'name': 'iPad Pro 13-inch (M4, Cellular)', 'boards': ['J721AP']},
    'iPad16,8': {'name': 'iPad Air 11-inch (M4, Wi-Fi)', 'boards': ['J707AP']},
    'iPad16,9': {'name': 'iPad Air 11-inch (M4, Cellular)', 'boards': ['J708AP']},
    'iPad16,10': {'name': 'iPad Air 13-inch (M4, Wi-Fi)', 'boards': ['J737AP']},
    'iPad16,11': {'name': 'iPad Air 13-inch (M4, Cellular)', 'boards': ['J738AP']},
    'iPad17,1': {'name': 'iPad Pro 11-inch (M5, Wi-Fi)', 'boards': ['J817AP']},
    'iPad17,2': {'name': 'iPad Pro 11-inch (M5, Cellular)', 'boards': ['J818AP']},
    'iPad17,3': {'name': 'iPad Pro 13-inch (M5, Wi-Fi)', 'boards': ['J820AP']},
    'iPad17,4': {'name': 'iPad Pro 13-inch (M5, Cellular)', 'boards': ['J821AP']},
}

MODELS = {**IPHONE_MODELS, **IPAD_MODELS}
